version: "3.7"
services:
  app:
    build:
      args:
        user: bookshelf
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: bookshelf
    container_name: lsp-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - bookshelf

  db:
    image: mysql:5.7
    container_name: bookshelf-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_bookshelf
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_PASSWORD: 1
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - bookshelf
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-lsp
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_USER: root
      MYSQL_PASSWORD: 1
      SERVICE_TAGS: dev
      SERVICE_NAME: phpmyadmin
    ports:
      - 8044:83
    networks:
      - bookshelf

  nginx:
    image: nginx:alpine
    container_name: bookshelf-nginx
    restart: unless-stopped
    ports:
      - 8040:82
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - bookshelf
networks:
  bookshelf:
    driver: bridge
